//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace DRProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LmsSortDataServiceSoapBinding", Namespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Vector))]
    public partial class LmsSortDataServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback setDaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback transRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback transCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback transSortOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback transProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback transSortLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback transSortProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback transOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback transSortAssigmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback transStatusAlarmOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrResetBuinessCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback runOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback invokeServiceOperationCompleted;
        
        /// <remarks/>
        public LmsSortDataServiceService() {
            this.Url = "http://10.141.191.237:8080/lms/services/LmsSortDataService";
        }
        
        /// <remarks/>
        public event getDaoCompletedEventHandler getDaoCompleted;
        
        /// <remarks/>
        public event setDaoCompletedEventHandler setDaoCompleted;
        
        /// <remarks/>
        public event transRouteCompletedEventHandler transRouteCompleted;
        
        /// <remarks/>
        public event transCustomerCompletedEventHandler transCustomerCompleted;
        
        /// <remarks/>
        public event transSortOrderCompletedEventHandler transSortOrderCompleted;
        
        /// <remarks/>
        public event transProductCompletedEventHandler transProductCompleted;
        
        /// <remarks/>
        public event transSortLineCompletedEventHandler transSortLineCompleted;
        
        /// <remarks/>
        public event transSortProcessCompletedEventHandler transSortProcessCompleted;
        
        /// <remarks/>
        public event transOrderStatusCompletedEventHandler transOrderStatusCompleted;
        
        /// <remarks/>
        public event transSortAssigmentCompletedEventHandler transSortAssigmentCompleted;
        
        /// <remarks/>
        public event transStatusAlarmCompletedEventHandler transStatusAlarmCompleted;
        
        /// <remarks/>
        public event getOrResetBuinessCacheCompletedEventHandler getOrResetBuinessCacheCompleted;
        
        /// <remarks/>
        public event runCompletedEventHandler runCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event invokeServiceCompletedEventHandler invokeServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDaoReturn")]
        public LmsSortDataDao getDao() {
            object[] results = this.Invoke("getDao", new object[0]);
            return ((LmsSortDataDao)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDao(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDao", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public LmsSortDataDao EndgetDao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LmsSortDataDao)(results[0]));
        }
        
        /// <remarks/>
        public void getDaoAsync() {
            this.getDaoAsync(null);
        }
        
        /// <remarks/>
        public void getDaoAsync(object userState) {
            if ((this.getDaoOperationCompleted == null)) {
                this.getDaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDaoOperationCompleted);
            }
            this.InvokeAsync("getDao", new object[0], this.getDaoOperationCompleted, userState);
        }
        
        private void OngetDaoOperationCompleted(object arg) {
            if ((this.getDaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDaoCompleted(this, new getDaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        public void setDao(LmsSortDataDao dao) {
            this.Invoke("setDao", new object[] {
                        dao});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetDao(LmsSortDataDao dao, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setDao", new object[] {
                        dao}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsetDao(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void setDaoAsync(LmsSortDataDao dao) {
            this.setDaoAsync(dao, null);
        }
        
        /// <remarks/>
        public void setDaoAsync(LmsSortDataDao dao, object userState) {
            if ((this.setDaoOperationCompleted == null)) {
                this.setDaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetDaoOperationCompleted);
            }
            this.InvokeAsync("setDao", new object[] {
                        dao}, this.setDaoOperationCompleted, userState);
        }
        
        private void OnsetDaoOperationCompleted(object arg) {
            if ((this.setDaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setDaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transRouteReturn")]
        public string transRoute(string batchNo) {
            object[] results = this.Invoke("transRoute", new object[] {
                        batchNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransRoute(string batchNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transRoute", new object[] {
                        batchNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransRoute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transRouteAsync(string batchNo) {
            this.transRouteAsync(batchNo, null);
        }
        
        /// <remarks/>
        public void transRouteAsync(string batchNo, object userState) {
            if ((this.transRouteOperationCompleted == null)) {
                this.transRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransRouteOperationCompleted);
            }
            this.InvokeAsync("transRoute", new object[] {
                        batchNo}, this.transRouteOperationCompleted, userState);
        }
        
        private void OntransRouteOperationCompleted(object arg) {
            if ((this.transRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transRouteCompleted(this, new transRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transCustomerReturn")]
        public string transCustomer(string batchNo) {
            object[] results = this.Invoke("transCustomer", new object[] {
                        batchNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransCustomer(string batchNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transCustomer", new object[] {
                        batchNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transCustomerAsync(string batchNo) {
            this.transCustomerAsync(batchNo, null);
        }
        
        /// <remarks/>
        public void transCustomerAsync(string batchNo, object userState) {
            if ((this.transCustomerOperationCompleted == null)) {
                this.transCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransCustomerOperationCompleted);
            }
            this.InvokeAsync("transCustomer", new object[] {
                        batchNo}, this.transCustomerOperationCompleted, userState);
        }
        
        private void OntransCustomerOperationCompleted(object arg) {
            if ((this.transCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transCustomerCompleted(this, new transCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transSortOrderReturn")]
        public string transSortOrder(string batchNo) {
            object[] results = this.Invoke("transSortOrder", new object[] {
                        batchNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransSortOrder(string batchNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transSortOrder", new object[] {
                        batchNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransSortOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transSortOrderAsync(string batchNo) {
            this.transSortOrderAsync(batchNo, null);
        }
        
        /// <remarks/>
        public void transSortOrderAsync(string batchNo, object userState) {
            if ((this.transSortOrderOperationCompleted == null)) {
                this.transSortOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransSortOrderOperationCompleted);
            }
            this.InvokeAsync("transSortOrder", new object[] {
                        batchNo}, this.transSortOrderOperationCompleted, userState);
        }
        
        private void OntransSortOrderOperationCompleted(object arg) {
            if ((this.transSortOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transSortOrderCompleted(this, new transSortOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transProductReturn")]
        public string transProduct() {
            object[] results = this.Invoke("transProduct", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransProduct(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transProduct", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransProduct(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transProductAsync() {
            this.transProductAsync(null);
        }
        
        /// <remarks/>
        public void transProductAsync(object userState) {
            if ((this.transProductOperationCompleted == null)) {
                this.transProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransProductOperationCompleted);
            }
            this.InvokeAsync("transProduct", new object[0], this.transProductOperationCompleted, userState);
        }
        
        private void OntransProductOperationCompleted(object arg) {
            if ((this.transProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transProductCompleted(this, new transProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transSortLineReturn")]
        public string transSortLine(string sortLineObject, string opType) {
            object[] results = this.Invoke("transSortLine", new object[] {
                        sortLineObject,
                        opType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransSortLine(string sortLineObject, string opType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transSortLine", new object[] {
                        sortLineObject,
                        opType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransSortLine(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transSortLineAsync(string sortLineObject, string opType) {
            this.transSortLineAsync(sortLineObject, opType, null);
        }
        
        /// <remarks/>
        public void transSortLineAsync(string sortLineObject, string opType, object userState) {
            if ((this.transSortLineOperationCompleted == null)) {
                this.transSortLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransSortLineOperationCompleted);
            }
            this.InvokeAsync("transSortLine", new object[] {
                        sortLineObject,
                        opType}, this.transSortLineOperationCompleted, userState);
        }
        
        private void OntransSortLineOperationCompleted(object arg) {
            if ((this.transSortLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transSortLineCompleted(this, new transSortLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transSortProcessReturn")]
        public string transSortProcess(string sortProcessObject, string opType) {
            object[] results = this.Invoke("transSortProcess", new object[] {
                        sortProcessObject,
                        opType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransSortProcess(string sortProcessObject, string opType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transSortProcess", new object[] {
                        sortProcessObject,
                        opType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransSortProcess(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transSortProcessAsync(string sortProcessObject, string opType) {
            this.transSortProcessAsync(sortProcessObject, opType, null);
        }
        
        /// <remarks/>
        public void transSortProcessAsync(string sortProcessObject, string opType, object userState) {
            if ((this.transSortProcessOperationCompleted == null)) {
                this.transSortProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransSortProcessOperationCompleted);
            }
            this.InvokeAsync("transSortProcess", new object[] {
                        sortProcessObject,
                        opType}, this.transSortProcessOperationCompleted, userState);
        }
        
        private void OntransSortProcessOperationCompleted(object arg) {
            if ((this.transSortProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transSortProcessCompleted(this, new transSortProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transOrderStatusReturn")]
        public string transOrderStatus(string orderStatusObject, string opType) {
            object[] results = this.Invoke("transOrderStatus", new object[] {
                        orderStatusObject,
                        opType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransOrderStatus(string orderStatusObject, string opType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transOrderStatus", new object[] {
                        orderStatusObject,
                        opType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransOrderStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transOrderStatusAsync(string orderStatusObject, string opType) {
            this.transOrderStatusAsync(orderStatusObject, opType, null);
        }
        
        /// <remarks/>
        public void transOrderStatusAsync(string orderStatusObject, string opType, object userState) {
            if ((this.transOrderStatusOperationCompleted == null)) {
                this.transOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransOrderStatusOperationCompleted);
            }
            this.InvokeAsync("transOrderStatus", new object[] {
                        orderStatusObject,
                        opType}, this.transOrderStatusOperationCompleted, userState);
        }
        
        private void OntransOrderStatusOperationCompleted(object arg) {
            if ((this.transOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transOrderStatusCompleted(this, new transOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transSortAssigmentReturn")]
        public string transSortAssigment(string sortAssigmentObject, string opType) {
            object[] results = this.Invoke("transSortAssigment", new object[] {
                        sortAssigmentObject,
                        opType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransSortAssigment(string sortAssigmentObject, string opType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transSortAssigment", new object[] {
                        sortAssigmentObject,
                        opType}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransSortAssigment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transSortAssigmentAsync(string sortAssigmentObject, string opType) {
            this.transSortAssigmentAsync(sortAssigmentObject, opType, null);
        }
        
        /// <remarks/>
        public void transSortAssigmentAsync(string sortAssigmentObject, string opType, object userState) {
            if ((this.transSortAssigmentOperationCompleted == null)) {
                this.transSortAssigmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransSortAssigmentOperationCompleted);
            }
            this.InvokeAsync("transSortAssigment", new object[] {
                        sortAssigmentObject,
                        opType}, this.transSortAssigmentOperationCompleted, userState);
        }
        
        private void OntransSortAssigmentOperationCompleted(object arg) {
            if ((this.transSortAssigmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transSortAssigmentCompleted(this, new transSortAssigmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("transStatusAlarmReturn")]
        public string transStatusAlarm(string alarmDataObject) {
            object[] results = this.Invoke("transStatusAlarm", new object[] {
                        alarmDataObject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintransStatusAlarm(string alarmDataObject, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("transStatusAlarm", new object[] {
                        alarmDataObject}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndtransStatusAlarm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transStatusAlarmAsync(string alarmDataObject) {
            this.transStatusAlarmAsync(alarmDataObject, null);
        }
        
        /// <remarks/>
        public void transStatusAlarmAsync(string alarmDataObject, object userState) {
            if ((this.transStatusAlarmOperationCompleted == null)) {
                this.transStatusAlarmOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransStatusAlarmOperationCompleted);
            }
            this.InvokeAsync("transStatusAlarm", new object[] {
                        alarmDataObject}, this.transStatusAlarmOperationCompleted, userState);
        }
        
        private void OntransStatusAlarmOperationCompleted(object arg) {
            if ((this.transStatusAlarmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transStatusAlarmCompleted(this, new transStatusAlarmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        public void getOrResetBuinessCache() {
            this.Invoke("getOrResetBuinessCache", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOrResetBuinessCache(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOrResetBuinessCache", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndgetOrResetBuinessCache(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void getOrResetBuinessCacheAsync() {
            this.getOrResetBuinessCacheAsync(null);
        }
        
        /// <remarks/>
        public void getOrResetBuinessCacheAsync(object userState) {
            if ((this.getOrResetBuinessCacheOperationCompleted == null)) {
                this.getOrResetBuinessCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrResetBuinessCacheOperationCompleted);
            }
            this.InvokeAsync("getOrResetBuinessCache", new object[0], this.getOrResetBuinessCacheOperationCompleted, userState);
        }
        
        private void OngetOrResetBuinessCacheOperationCompleted(object arg) {
            if ((this.getOrResetBuinessCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrResetBuinessCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        public void run() {
            this.Invoke("run", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginrun(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("run", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void Endrun(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void runAsync() {
            this.runAsync(null);
        }
        
        /// <remarks/>
        public void runAsync(object userState) {
            if ((this.runOperationCompleted == null)) {
                this.runOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunOperationCompleted);
            }
            this.InvokeAsync("run", new object[0], this.runOperationCompleted, userState);
        }
        
        private void OnrunOperationCompleted(object arg) {
            if ((this.runCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        public void test() {
            this.Invoke("test", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintest(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("test", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void Endtest(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void testAsync() {
            this.testAsync(null);
        }
        
        /// <remarks/>
        public void testAsync(object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[0], this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sortline.service.datainterface.lms.neusoft.com", ResponseNamespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
        [return: System.Xml.Serialization.SoapElementAttribute("invokeServiceReturn")]
        public object invokeService(string type, string operName, object[] paramValues, string targetNamespace, string[] paramTypes, string url) {
            object[] results = this.Invoke("invokeService", new object[] {
                        type,
                        operName,
                        paramValues,
                        targetNamespace,
                        paramTypes,
                        url});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvokeService(string type, string operName, object[] paramValues, string targetNamespace, string[] paramTypes, string url, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invokeService", new object[] {
                        type,
                        operName,
                        paramValues,
                        targetNamespace,
                        paramTypes,
                        url}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndinvokeService(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void invokeServiceAsync(string type, string operName, object[] paramValues, string targetNamespace, string[] paramTypes, string url) {
            this.invokeServiceAsync(type, operName, paramValues, targetNamespace, paramTypes, url, null);
        }
        
        /// <remarks/>
        public void invokeServiceAsync(string type, string operName, object[] paramValues, string targetNamespace, string[] paramTypes, string url, object userState) {
            if ((this.invokeServiceOperationCompleted == null)) {
                this.invokeServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeServiceOperationCompleted);
            }
            this.InvokeAsync("invokeService", new object[] {
                        type,
                        operName,
                        paramValues,
                        targetNamespace,
                        paramTypes,
                        url}, this.invokeServiceOperationCompleted, userState);
        }
        
        private void OninvokeServiceOperationCompleted(object arg) {
            if ((this.invokeServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeServiceCompleted(this, new invokeServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://10.141.191.237:8080/lms/services/LmsSortDataService")]
    public partial class LmsSortDataDao {
        
        private object sqlMapField;
        
        private object[] todaySortedOrdersField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object sqlMap {
            get {
                return this.sqlMapField;
            }
            set {
                this.sqlMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] todaySortedOrders {
            get {
                return this.todaySortedOrdersField;
            }
            set {
                this.todaySortedOrdersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Vector {
        
        private object[] itemField;
        
        /// <remarks/>
        public object[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getDaoCompletedEventHandler(object sender, getDaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LmsSortDataDao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LmsSortDataDao)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void setDaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transRouteCompletedEventHandler(object sender, transRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transCustomerCompletedEventHandler(object sender, transCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transSortOrderCompletedEventHandler(object sender, transSortOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transSortOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transSortOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transProductCompletedEventHandler(object sender, transProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transSortLineCompletedEventHandler(object sender, transSortLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transSortLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transSortLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transSortProcessCompletedEventHandler(object sender, transSortProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transSortProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transSortProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transOrderStatusCompletedEventHandler(object sender, transOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transSortAssigmentCompletedEventHandler(object sender, transSortAssigmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transSortAssigmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transSortAssigmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void transStatusAlarmCompletedEventHandler(object sender, transStatusAlarmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transStatusAlarmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transStatusAlarmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getOrResetBuinessCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void runCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void testCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void invokeServiceCompletedEventHandler(object sender, invokeServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}
